//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektlabor.covid19login.adminpanel.Properties.langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projektlabor.covid19login.adminpanel.Properties.langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer/Administrator-ID.
        /// </summary>
        public static string config_adminid {
            get {
                return ResourceManager.GetString("config.adminid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        public static string config_button_newpw {
            get {
                return ResourceManager.GetString("config.button.newpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig.
        /// </summary>
        public static string config_button_reset {
            get {
                return ResourceManager.GetString("config.button.reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string config_button_save {
            get {
                return ResourceManager.GetString("config.button.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rohmaterial Kopieren.
        /// </summary>
        public static string config_currepted_copy {
            get {
                return ResourceManager.GetString("config.currepted.copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr eingegebener Schlüssel ist richtig, aber die Datei konnte geladen werden.
        ///Leider ist das Dateiformat kapput und kann nicht geladen werden.
        ///Möchten Sie eine neue Konifiguration anlegen?
        ///Unterhalb können sie auch das Rohmaterial, welches geladen werden konnte Kopieren..
        /// </summary>
        public static string config_currupted_info {
            get {
                return ResourceManager.GetString("config.currupted.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string config_currupted_no {
            get {
                return ResourceManager.GetString("config.currupted.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration is Fehlerhaft.
        /// </summary>
        public static string config_currupted_title {
            get {
                return ResourceManager.GetString("config.currupted.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu erstellen.
        /// </summary>
        public static string config_currupted_yes {
            get {
                return ResourceManager.GetString("config.currupted.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP/Domain (Remote Server).
        /// </summary>
        public static string config_host {
            get {
                return ResourceManager.GetString("config.host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string config_loaderr_close {
            get {
                return ResourceManager.GetString("config.loaderr.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim laden.
        /// </summary>
        public static string config_loaderr_title {
            get {
                return ResourceManager.GetString("config.loaderr.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim erstellen der Konfiguration.
        /// </summary>
        public static string config_new_error {
            get {
                return ResourceManager.GetString("config.new.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string config_new_error_button {
            get {
                return ResourceManager.GetString("config.new.error.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein neues Passwort an..
        /// </summary>
        public static string config_new_pass_text {
            get {
                return ResourceManager.GetString("config.new.pass.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        public static string config_new_pass_title {
            get {
                return ResourceManager.GetString("config.new.pass.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string config_newpw_no {
            get {
                return ResourceManager.GetString("config.newpw.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort eingeben.
        /// </summary>
        public static string config_newpw_title {
            get {
                return ResourceManager.GetString("config.newpw.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string config_newpw_yes {
            get {
                return ResourceManager.GetString("config.newpw.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Konfigurationsdatei gefunden, möchten Sie eine neue erstellen?.
        /// </summary>
        public static string config_notexisting_info {
            get {
                return ResourceManager.GetString("config.notexisting.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string config_notexisting_no {
            get {
                return ResourceManager.GetString("config.notexisting.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationsdatei existiert nicht.
        /// </summary>
        public static string config_notexisting_title {
            get {
                return ResourceManager.GetString("config.notexisting.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string config_notexisting_yes {
            get {
                return ResourceManager.GetString("config.notexisting.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string config_pass_cancle {
            get {
                return ResourceManager.GetString("config.pass.cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        public static string config_pass_ok {
            get {
                return ResourceManager.GetString("config.pass.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort benötigt.
        /// </summary>
        public static string config_pass_title {
            get {
                return ResourceManager.GetString("config.pass.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port-Nummer (Remote Server).
        /// </summary>
        public static string config_port {
            get {
                return ResourceManager.GetString("config.port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA-Schlüssel.
        /// </summary>
        public static string config_rsa {
            get {
                return ResourceManager.GetString("config.rsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string config_save_button {
            get {
                return ResourceManager.GetString("config.save.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafter Schlüssel (Private Key).
        /// </summary>
        public static string config_save_key {
            get {
                return ResourceManager.GetString("config.save.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafter Port.
        /// </summary>
        public static string config_save_port {
            get {
                return ResourceManager.GetString("config.save.port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Fehler.
        /// </summary>
        public static string config_save_unknown {
            get {
                return ResourceManager.GetString("config.save.unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhafte AdminId.
        /// </summary>
        public static string config_save_userid {
            get {
                return ResourceManager.GetString("config.save.userid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration.
        /// </summary>
        public static string config_title {
            get {
                return ResourceManager.GetString("config.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut versuchen.
        /// </summary>
        public static string config_wrongpw_retry {
            get {
                return ResourceManager.GetString("config.wrongpw.retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Passwort.
        /// </summary>
        public static string config_wrongpw_title {
            get {
                return ResourceManager.GetString("config.wrongpw.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string global_button_cancel {
            get {
                return ResourceManager.GetString("global.button.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        public static string global_button_ok {
            get {
                return ResourceManager.GetString("global.button.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authcode angeben.
        /// </summary>
        public static string main_startup_askauth_title {
            get {
                return ResourceManager.GetString("main.startup.askauth.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut versuchen.
        /// </summary>
        public static string main_startup_getauth_retry {
            get {
                return ResourceManager.GetString("main.startup.getauth.retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektlabor | Covid 19 Anmeldung | Administrator-Interface.
        /// </summary>
        public static string main_title {
            get {
                return ResourceManager.GetString("main.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Authcode ist abgelaufen..
        /// </summary>
        public static string request_error_common_authexpired {
            get {
                return ResourceManager.GetString("request.error.common.authexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Authcode ist falsch..
        /// </summary>
        public static string request_error_common_authinvalid {
            get {
                return ResourceManager.GetString("request.error.common.authinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler bei der Datenbankverbindung auf dem Server aufgetreteten..
        /// </summary>
        public static string request_error_common_database {
            get {
                return ResourceManager.GetString("request.error.common.database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Account ist gesperrt (Eingefroren) und kann nicht genutzt werden..
        /// </summary>
        public static string request_error_common_frozen {
            get {
                return ResourceManager.GetString("request.error.common.frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung mit dem Server konnte nicht hergestellt werden. I/O-Error.
        /// </summary>
        public static string request_error_common_io {
            get {
                return ResourceManager.GetString("request.error.common.io", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei der Anfrage.
        /// </summary>
        public static string request_error_common_title {
            get {
                return ResourceManager.GetString("request.error.common.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server konnte die Email mit dem Auth-code nicht absenden..
        /// </summary>
        public static string request_error_email_text {
            get {
                return ResourceManager.GetString("request.error.email.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-Fehler.
        /// </summary>
        public static string request_error_email_title {
            get {
                return ResourceManager.GetString("request.error.email.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Authentifizierungs-Schlüssel scheint mit dem des Servers nicht über ein zu stimmen..
        /// </summary>
        public static string request_error_tech_authkey {
            get {
                return ResourceManager.GetString("request.error.tech.authkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Server hat einen Handler-Fehler zurückgegeben..
        /// </summary>
        public static string request_error_tech_handler {
            get {
                return ResourceManager.GetString("request.error.tech.handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Account hat keine Rechte diese Aktion anzufragen..
        /// </summary>
        public static string request_error_tech_permission {
            get {
                return ResourceManager.GetString("request.error.tech.permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technischer Fehler.
        /// </summary>
        public static string request_error_tech_title {
            get {
                return ResourceManager.GetString("request.error.tech.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein unbekannter Fehler aufgetreten..
        /// </summary>
        public static string request_error_tech_unknown {
            get {
                return ResourceManager.GetString("request.error.tech.unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bitte fragen Sie einen Techniker um hilfe bei diesem Problem..
        /// </summary>
        public static string requests_error_tech_help {
            get {
                return ResourceManager.GetString("requests.error.tech.help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade/Erstelle Konfiguration.
        /// </summary>
        public static string startup_askconfig {
            get {
                return ResourceManager.GetString("startup.askconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Text entspricht nicht dem Authcode-Format..
        /// </summary>
        public static string startup_getauth_invalid {
            get {
                return ResourceManager.GetString("startup.getauth.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sende 2FA-Authcode Anfrage.
        /// </summary>
        public static string startup_requestauth {
            get {
                return ResourceManager.GetString("startup.requestauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden des Authcodes.
        /// </summary>
        public static string startup_sendauth {
            get {
                return ResourceManager.GetString("startup.sendauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Führe login durch.
        /// </summary>
        public static string startup_title {
            get {
                return ResourceManager.GetString("startup.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Account soll nach 6 Wochen gelöscht werden..
        /// </summary>
        public static string ui_register_autodeleteaccount {
            get {
                return ResourceManager.GetString("ui.register.autodeleteaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir versichern, dass ihr Konto nach 4 und allerspätestens 6 Wochen gelöscht wird. Wenn Sie innerhalb dieser Zeitspanne im Projektlabor waren, wird diese Zeit zurückgesetzt..
        /// </summary>
        public static string ui_register_autodeleteaccount_text {
            get {
                return ResourceManager.GetString("ui.register.autodeleteaccount.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannen.
        /// </summary>
        public static string ui_register_button_scan {
            get {
                return ResourceManager.GetString("ui.register.button.scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (Optional).
        /// </summary>
        public static string ui_register_email {
            get {
                return ResourceManager.GetString("ui.register.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ui_register_error_street_number {
            get {
                return ResourceManager.GetString("ui.register.error.street_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string ui_register_firstname {
            get {
                return ResourceManager.GetString("ui.register.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string ui_register_lastname {
            get {
                return ResourceManager.GetString("ui.register.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wohnort.
        /// </summary>
        public static string ui_register_location {
            get {
                return ResourceManager.GetString("ui.register.location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine valide Email-Adresse an..
        /// </summary>
        public static string ui_register_opterror_email {
            get {
                return ResourceManager.GetString("ui.register.opterror.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string ui_register_plz {
            get {
                return ResourceManager.GetString("ui.register.plz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID-Code (Optional).
        /// </summary>
        public static string ui_register_rfid {
            get {
                return ResourceManager.GetString("ui.register.rfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halten Sie ihre RFID-Karte oder ihr Handy mit der RFID-App an den Scanner und lassen Sie ihre Karte scannen..
        /// </summary>
        public static string ui_register_rfid_text {
            get {
                return ResourceManager.GetString("ui.register.rfid.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte scannen sie ihre RFID-Karte.
        /// </summary>
        public static string ui_register_rfid_title {
            get {
                return ResourceManager.GetString("ui.register.rfid.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string ui_register_street {
            get {
                return ResourceManager.GetString("ui.register.street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        public static string ui_register_street_number {
            get {
                return ResourceManager.GetString("ui.register.street_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon (Optional).
        /// </summary>
        public static string ui_register_telephone {
            get {
                return ResourceManager.GetString("ui.register.telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erforderlich.
        /// </summary>
        public static string ui_registerinput_opterror_default {
            get {
                return ResourceManager.GetString("ui.registerinput.opterror.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlerhaft.
        /// </summary>
        public static string ui_registerinput_regexerror_default {
            get {
                return ResourceManager.GetString("ui.registerinput.regexerror.default", resourceCulture);
            }
        }
    }
}
